name: bargainbay cron

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:        

jobs:
  keep-awake:
    runs-on: ubuntu-latest

    steps:
      - name: Curl the Render App
        run: |
          curl -sSf https://bargainbay-06k1.onrender.com || echo "Ping failed"
